### ISSUE TITLE
README.md "How to Test it"

### ISSUE THREAD

**Issue by cleveranjos** [intersystems-community/intersystems-iris-dev-template#1]
This section
How to Test it
$ docker-compose exec iris iris session iris
IRISAPP>write ##class(dc.PackageSample.ObjectScript).Test()

should be
$ docker-compose exec iris iris session iris **-U IRISAPP**
IRISAPP>write ##class(dc.PackageSample.ObjectScript).Test()

**Comment by evshvarov** [comment]
Thanks @cleveranjos
